### ISSUE TITLE
Annotation saved to wrong group when created while logged out

### ISSUE THREAD

**Issue by seanh** [hypothesis/client#11]
1. Sign in
2. Focus group Foo (not Public)
3. Log out
4. Create a new annotation (you'll get a "You must sign in to create annotations" card)
5. Sign in

-> The focused group will be the one you lost had focused when you were last logged in: Foo. But the annotation's Post button will say Public, and if you save it, it'll be saved to Public.

![untitled screencast 25](https://cloud.githubusercontent.com/assets/22498/16526171/c8da949e-3fa7-11e6-8bbc-1232ce4b0d4c.gif)

**Comment by seanh** [comment]
If you do the same thing but create a reply instead of an annotation, same result plus "Message not available" card in place of parent annotation.

**Comment by lyzadanger** [comment]
The behavior has changed in both of these areas of the app.

At present, if you:

* Focus a private group
* Log out
* Select text; click "Annotate"

You'll see a login prompt. If you log in:

* You'll be returned to your last-focused group (the private group)
* Your pending draft is not retained, so there's no publish confusion

A while ago we disabled drafts for anonymous users because it created all sorts of headaches. Thus, there isn't a draft "waiting for you" for your selected text once you log in. It could be argued that there should be, in the longer term, but it's beyond the scope of this particular issue report.

The same for replies: You'll be prompted to log in; your reply won't "go somewhere weird" because it isn't created at all.
