### ISSUE TITLE
Implement a "User-focused" mode (for grading) in the client

### ISSUE THREAD

**Issue by seanh** [hypothesis/client#1241]
While the LMS app doesn't actually need the bouncer part of bouncer links to users, for grading it does need a way to tell the client to focus on one user's annotations. So implement just the client-side part of bouncer links for users

* The client should read some `#fragment` from the URL that makes it focus on just one user. (E.g. `#annotations:userid:seanh`, final format TBD)

* The client UI should look nice when in this user-filtered state: making it clear that a filer is active; which user is being shown; clear way to remove the filter.

* The client should auto-scroll the document to the user's first annotation

* The client should show an explanation message if the user has no annotations

* Etc

**Comment by jaredpdesigns** [comment]
@seanh and I had a call today where he provided a demo of how user-focused grading would work and I gleaned a few key takeaways:
- The user selection/pagination happens at a layer above the Hypothesis client via a LMS wrapper. The only indication of the current user selection in context of the Hypothesis client is by including a query search in the search bar. This is not ideal because if a user does in fact clear the search, the LMS layer would still indicate a specific user but the annotations sidebar would be reset to all annotations in the assignment.
- We should provide a way for _regular_ searching to happen without worrying about the scope of the current user (i.e I should still be able to do a string search or search for a specific tag).

Suggestions:
- We query the specific user without indicating it in the UI (i.e. provide a way to return specific annotations without relying on the search component, and remove any option to clear this query).
- Remove the ability from this instance of the search component to filter by user, but retain all other search query types.
- Annotations by the specific queried user should _look_ like a regular annotation but any indication of other users annotations (like a reply) should be visually muted to keep it clearer which annotations belong to the queried user.

**Comment by dwhly** [comment]
> We should provide a way for regular searching to happen without worrying about the scope of the current user (i.e I should still be able to do a string search or search for a specific tag).

Agree!  Spending the time to fix our current search interface (how tiny it is and how ungainly the user:username facet looks inside of it) so that you could more easily add to a current search might be the right approach.  Perhaps the facets should be lozenged the way they are in activity pages.

> We query the specific user without indicating it in the UI (i.e. provide a way to return specific annotations without relying on the search component, and remove any option to clear this query).

I'd counter that we not keep this info from the user.  *If* we want to make it immutable, then we could lock it down (lozenge can't be deleted or something).  Though you could make an argument that a user might be bothered that they couldn't do this.

**Comment by lyzadanger** [comment]
> Agree! Spending the time to fix our current search interface (how tiny it is and how ungainly the user:username facet looks inside of it) so that you could more easily add to a current search might be the right approach. Perhaps the facets should be lozenged the way they are in activity pages.

I agree that our search interface needs work. I'd like to decouple that, if at all possible, from the immediate work here, which is slated for delivery this sprint. I'd like to keep scope as focused as possible here to the MVP for the SpeedGrader context.

The good news is that the current WIP approach addresses nearly all of @jaredpdesigns' comments and thoughts above. There is a way to search "on top of" the user filter that does not interfere with the applied user filter, e.g.

**Comment by ajpeddakotla** [comment]
Agree with @lyzadanger's comment here on decoupling improvements to existing search interface right now. We can definitely work on this in the _very_ near future, and we'll have to address this problem again in the other LMS platforms. I'll write up a separate issue for this and link it.

**Comment by judell** [comment]
>  any indication of other users annotations (like a reply) should be
visually muted to keep
> it clearer which annotations belong to the queried user.

Correct. The original implementation of grading in the 2016 alpha had a
crude version of that, and it was well received.

**Comment by ajpeddakotla** [comment]
From a slack convo earlier: 
@dwhly requested a user story for design input on the UX for a filter-toggling element for a focused user. I'm including it in this card since it is a part of this work.

As a teacher, I'd like to switch between views of filtered searches and non-filtered searches, so that I can see annotations made by other students outside of the current user focus required for grading one student's annotations. Some reasons why I would like to use this feature is to see what other students may have written in a particular section of text, and compare annotations made by each student.

**Comment by jaredpdesigns** [comment]
![sidebar-filtering](https://user-images.githubusercontent.com/6108048/62501130-01308080-b785-11e9-9384-fedeabc2707b.jpg)

Attached is a mock-up including a few ideas about the filter toggle, with some notes:
- (top image): Default state, toggle button with `filter` icon indicating what is currently being shown with appropriate count in “Annotations” tab-label.
- (middle image): Clear search button next to filter toggle button and (possibly redundant) indication of how many filtered results are being shown.
- (bottom image): Alternative state of filter toggle with label “All annotations”.

Possible issues worth addressing:
-  It’s not very obvious that clicking the filter button toggles scoped annotations to un-scoped annotations (i.e. All annotations) but I’d argue this is OK. In general, we want annotations to be scoped by user with broadening the scope to be achievable but not preferred.
-  In the current client, once a user performs a search using the search input we remove the tabs for “Annotations / Page Notes / Orphans” and replace it with the “Clear search” button and an indication of how many results are returned. I like that the number indicator next to the annotations tab label implies how many are being shown currently, and reinforces that I’m looking at annotations. Question: if I’m performing a search shouldn’t that filter apply to annotations, page notes and orphans if I haven’t cleared the search?

**Comment by dwhly** [comment]
Thanks Jared.

Side note: Currently (just as a reminder to all), we don't show the tabs when a search is active.  IIRC this is because the search consolidates results from *all* three tabs (annotations, page notes, orphans).  I *think* this is probably the right call.  But: if we're going to change the behavior, we should articulate the reasoning behind the change and apply it consistently.

> It’s not very obvious that clicking the filter button toggles scoped annotations to un-scoped annotations

I agree.  In fact-- it kind of comes across as meaning exactly the opposite of what it says. (i.e when it says "Annotations by username" and you click it, you get the opposite "Annotations by All"). This is the reverse of the Play vs Pause button sense (Good SE [post here](https://ux.stackexchange.com/questions/1318/should-a-toggle-button-show-its-current-state-or-the-state-to-which-it-will-chan)).   

I do think it's worth exploring alternative implementations that would make such a toggle more explicit.  Specifically I think we want it to be very clear which state the toggle is in, and what happens when the toggle changes to the opposite state.

> I’d argue this is OK. In general, we want annotations to be scoped by user with broadening the scope to be achievable but not preferred.

Aren't we implementing this so that users can have this capability?  From the user story above, I don't see a suggestion that we'd prefer people not do this.  Regardless, we should try to be as clear as we can about how things work.

Q: When it says "Annotations by username" are you imagining that the actual username would be there, or only the word "username"?

**Comment by jaredpdesigns** [comment]
@lyzadanger @dwhly 

![sidebar-filtering-final](https://user-images.githubusercontent.com/6108048/62649552-c8adb580-b8f0-11e9-9f0e-052ba5e927ed.jpg)

Here’s a rendering with what we discussed in terms of options and layout. In addition, I put together a Codepen that includes a proposed structure for the the toggle element built on top of what’s already in the sidebar’s CSS: [https://codepen.io/jaredpdesigns/pen/OKvJyr](https://codepen.io/jaredpdesigns/pen/OKvJyr)

Not sure if this is usable or you’re hoping for a different implementation but one nice plus of using HTML elements instead of an SVG for the toggle is a subtle transition we can use.

**Comment by lyzadanger** [comment]
With the nit fixed in https://github.com/hypothesis/client/pull/1347 I think we can consider this complete and close-able!
