### ISSUE TITLE
Determine if decayingInterval is at risk for stack limit

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#1285]
time.js has a function called `decayingInterval` which calls a private function called `update` over and over based on a timeout. 

- See if the stack trace ever gets unreasonable long with many annotations.
- If it does, create a non-recursive solution which does not burned the client with poor performance.

**Comment by robertknight** [comment]
A `setTimeout` callback is executed in a different turn of the event loop than the original call to `setTimeout`, so the stack is not actually growing each time it is called. However, for ease of debugging, Chrome keeps track of what code caused the current turn of the event loop to start (eg. a `setTimeout` callback or a Promise callback) and then tries to stitch together an "async" [stack trace](https://v8.dev/blog/fast-async#improved-developer-experience). So wherever you see "async" in an error stack or the call stack, that actually indicates a stack from an earlier event. You're not the only person to experience this confusion.

The `decayingInterval` function is designed to update something proportionally to how recent a value is. eg. A timestamp that says "N seconds ago" needs to be refreshed more frequently than one that says "N hours ago". This timeout quickly slows down its refresh rate as the timestamps gets older and needs refreshing less often.

I'll close this as I'm pretty sure there isn't an issue here, please let me know if you see something that makes you think otherwise.
