### ISSUE TITLE
Iteration: Show number of annotations in Grading Mode

### ISSUE THREAD

**Issue by klemay** [hypothesis/client#1296]
Part of https://github.com/hypothesis/client/issues/1241. 

## User Story
As a teacher, I require my students to create at least 5 annotations for each assigned reading. When I use the grading mode to see just one student's annotations, I want to easily see _how many_ annotations they made. 

## Background
Currently, the user-focused mode toggle looks like this:

![](https://user-images.githubusercontent.com/439947/62801013-c72beb00-bab2-11e9-99cb-ef95453c9c77.png)

![](https://user-images.githubusercontent.com/439947/62800978-b8ddcf00-bab2-11e9-9d49-32075ba78177.png)

We need to:
- [x] Agree on visual design for this feature
- [x] Make sure this is in harmony/consistent with the way search works in the client
- [x] Ensure the developers have a clear path to implementing this
- [ ] Build it!

**Comment by jaredpdesigns** [comment]
Based on @lyzadanger work on this [here](https://github.com/hypothesis/client/pull/1293)—is the pattern that we show the standard `Annotations^24 | Page Notes^4` tabs when we’re showing all tabs? I wasn’t aware that we’d allow users to view anything other than annotations in the context of grading. Having an option to also view page notes seems to step further back into complexity of navigating where a user currently is when there is still a top-level control to jump directly back to a single user’s annotations only.

I’m trying to understand that if we were come up with a pattern for showing quantity of annotations currently shown we take into account the toggle between:

- User focused
- User focused + search
- All annotations
- All annotations + search

Ideally coming up with a pattern that is similar enough for the user to understand what they are seeing. I’m not really loving having sandwiched areas of the sidebar that designate different levels of information. I’d love to arrive at a pattern that takes these cases into account for the purpose of the grading tool without necessarily using the same patterns we use elsewhere in the sidebar.

I’ll think about this some more but wanted to confirm my understanding for the way it’s supposed to work before prescribing change.

**Comment by klemay** [comment]
@jaredpdesigns, the pattern shown at https://github.com/hypothesis/client/pull/1293 is indeed our standard `Annotations^24 | Page Notes^4` component. Here's how it looks in the current client:

Sidebar over a page with Annotations, Page Notes, and Orphans (web.hypothes.is):
<img width="477" alt="Screen Shot 2019-08-13 at 5 34 42 PM" src="https://user-images.githubusercontent.com/12087705/62979017-ae903d80-bdf0-11e9-91f5-c07eb3f2dfcb.png">

Same sidebar, with a search term entered, which appears in 1 annotation and 1 page note:
<img width="481" alt="Screen Shot 2019-08-13 at 5 36 23 PM" src="https://user-images.githubusercontent.com/12087705/62979101-e7c8ad80-bdf0-11e9-927f-d6d96420d70a.png">

**Comment by jaredpdesigns** [comment]
I really like the work @lyzadanger was already doing so I iterated on that idea a bit to try and reach a pattern we can use throughout the sidebar:

**Filtered by user**

- Basically what we already have, but I think there’s room for shortening the label of the button to “+ Show all”.
- Also like the idea of bolding count and whom we are filtering by. 
- I think if a user’s name was rather long we could wrap it to two lines and keep the button in the same position on the right/top of the box.

![sidebar-annotation-numbers-user](https://user-images.githubusercontent.com/6108048/62987953-286afb80-bdde-11e9-808c-a3f182bae884.jpg)

**All annotations**

- For at least the grading tool I think I’d prefer hiding the tabs for Annotations/Page notes since by default we are loading a filtered view, I’d like to hear a good argument for keeping them their in this particular context.

![sidebar-annotation-numbers-everyone](https://user-images.githubusercontent.com/6108048/62988008-6536f280-bdde-11e9-9527-3e4923cd591a.jpg)

**Search results**

- I like the idea of standardizing the pattern we’re establishing here, and think this might be it, we can even pull the search results into a card like this outside of the grading tool.

![sidebar-annotation-numbers-search](https://user-images.githubusercontent.com/6108048/62987982-459fca00-bdde-11e9-8b06-31862a4cfb60.jpg)

**Comment by dwhly** [comment]
Thanks for these mocks!

> Basically what we already have, but I think there’s room for shortening the label of the button to “+ Show all”.

I'm not sure "all" is clear (at least to me).  I think if I thought about it, and really focused on the word "only" at the end of the phrase, then I'd probably guess that "all" meant "everyone" but it doesn't seem immediately clear.

> I think if a user’s name was rather long we could wrap it to two lines and keep the button in the same position on the right/top of the box.

It seems like it would be good to be using long display names in our design mocks-- or at least to include them so that we can see what the outlier cases are, and what the behavior is when they're present.  

These mocks also don't show what a combination of scoped user and search term would look like.  Particularly important given the space constraints and the fact that these can be used in combination.

Also, given that we are thinking to a component library, what is the design rationale for a black (dark brown) button motif in most places versus a white button motif in others?  We should either standardize, or have a clear line of thinking as to what we're using where and why.

Also, can we confirm that the width of this mockup is the same as is present by default in the sidebar?  I know there was a question about that previously.

> I think I’d prefer hiding the tabs for Annotations/Page notes since by default we are loading a filtered view

I'm pretty sure they are already gone, right?  Totally agree if they are not, but I thought this was already decided.

**Comment by klemay** [comment]
> These mocks also don't show what a combination of scoped user and search term would look like. Particularly important given the space constraints and the fact that these can be used in combination.

The SpeedGrader UI has been shipped, so here is the current state of things in production:

![current-speedgrader](https://user-images.githubusercontent.com/12087705/63031789-9963ef00-be82-11e9-975d-2df109553306.png)

Notes:

- The language of the "Show all" button is part of the existing UI; I'd recommend creating & prioritizing a separate issue if we want to change it, to keep the scope of this issue as tight as possible
- Agreed that using long names in display mocks is a good idea!
- The annotations / page notes tabs are indeed hidden by default when the user-focused mode is launched (see Item 1 in the screenshot above).

**Comment by lyzadanger** [comment]
The rule of thumb for tabs is: any time any sort of filtering is applied—be it a user focus or a search—the tabs are not displayed, and the displayed results include all kinds of annotations (page notes, annotations, orphans).

**Comment by jaredpdesigns** [comment]
Capturing latest iteration based on feedback in Slack:

![sidebar-annotation-numbers](https://user-images.githubusercontent.com/6108048/63060536-4728cb00-be8e-11e9-8c71-ebbac6e01cbb.jpg)

**Comment by jaredpdesigns** [comment]
Latest iteration including a narrower client width for testing long names and use of current `x Clear search` pattern:

![sidebar-annotation-numbers](https://user-images.githubusercontent.com/6108048/63203808-a40eb780-c02d-11e9-94c5-9c1433cb6685.jpg)

**Comment by klemay** [comment]
Thanks, @jaredpdesigns! This is ready to hand off to developers for implementation. Notably:

- The user-focus toggle card (where it says "Showing Sebastien Maurice Flaubert only | [+ Show all]" has a reduced height to take up as little screen real estate as possible
- "Show all" button becomes "+ Show all"
- "Only Sebastien Maurice Flaubert"  becomes "Only selected student" (to avoid line-wrapping issues in buttons, and to sound a bit less awkward overall)
- "Sharing XX Annotations" shown above the annotation cards in student-focused mode
- Use the existing pattern for showing / clearing search results

**Comment by seanh** [comment]
@klemay Typo: "Sharing XX Annotations" -> "_Showing_ XX Annotations"?

**Comment by jaredpdesigns** [comment]
Revised the mock-up to clarify icons on buttons and adjust the width of the client to the default of `450px`.

![sidebar-annotation-numbers](https://user-images.githubusercontent.com/6108048/63471788-d8a6b880-c40b-11e9-8919-7bac886315c9.jpg)

Additionally, I produced a light version of the HTML/CSS needed to add the new elements: [https://codepen.io/jaredpdesigns/pen/GRKNXBd](https://codepen.io/jaredpdesigns/pen/GRKNXBd).

**Notes:**
- I attempted to use as many classes as we’re currently using and added the following:

``` scss
.thread-list__card--short {
  padding-bottom: 5px;
  padding-top: 5px;
}

.annotation-toggle {
  align-items: center;
  display: flex;
  &__label {
    font-size: 13px;
    flex: 1 1;
    line-height: 17px;
    margin-right: 10px;
    padding: calc((30px - 17px)/2) 0; // height of button - lineheight / 2 for equal balance when wrapping long names
  }
  .primary-action-btn {
    align-self: flex-start;
    flex-shrink: 0;
  }
  + * { margin-top: 10px; }
}

.annotation-count {
  font-size: 13px;
  font-weight: bold;
  line-height: 17px;
}
```
- The structure for the new indicator follows a simple structure:
``` html
<div class="thread-list__card thread-list__card--short annotation-toggle">
  <div class="annotation-toggle__label”>
    Showing <strong>John Jacob Jingleheimer Schmidt</strong> only
  </div>
  <button class="primary-action-btn primary-action-btn--short" title="Show all annotations for this reading"
>Show all</button>
</div>
```
- Not sure if there is a simpler, more global class to assign to adjust the text-size for the annotation count:
``` html
<div class="annotation-count">
  Showing 34 annotations
</div>
```

**Comment by seanh** [comment]
The last mockup (the one with no icons on the buttons) looks good to me but I'd like to make one request:

Let's **not** change the button label from the current _Show only **Sebastian Maurice Flaubert**_ to _Only selected student_. I think _Only selected student_ has some issues:

* It doesn't start with a verb, which makes it less clear that it's an action button and what it does. See previous discussion of why we previously changed this _from_ a label starting with "Only" to one that starts with "Show": https://hypothes-is.slack.com/archives/C0C6BDS1H/p1565795658010200?thread_ts=1565793879.004700&cid=C0C6BDS1H (and PR: https://github.com/hypothesis/client/pull/1305)
* The name of the focused student is no longer displayed anywhere in the client
* It introduces the phrase "selected student" which I believe is inappropriate. A "selected" object in the UI is something the user has selected, e.g. by clicking on. In this instance there is no selected student as such. The student who is currently being graded in the LMS is not really the "selected" student.

Also, I don't think there's nothing wrong with the existing _Show only **Sebastian Maurice Flaubert**_ label. In particular, this label is not too long:

![Screenshot from 2019-08-27 13-44-50](https://user-images.githubusercontent.com/22498/63772402-ed35f580-c8d0-11e9-9bf5-670f651af8b3.png)

So what I'm suggesting is that we go with Jared's most recently posted design above but just change the button label back to _Show only **Sebastian Maurice Flaubert**_.

**Comment by seanh** [comment]
Can I ask that we move any more discussion of changing the existing text labels to a separate card? This card is for showing the number of annotations (_As a teacher ... [w]hen I use the grading mode to see just one student's annotations, I want to easily see how many annotations they made_). We'd like to ship this user story in the current (three week) sprint and we're now on the last week of that sprint. So it might be a good idea to keep this card focused on the problem at hand and the minimal changes we can ship this week to fix that problem for our users, and make separate cards for other issues
