### ISSUE TITLE
sidebar floats left in narrow window

### ISSUE THREAD

**Issue by judell** [hypothesis/client#1308]
![image](https://user-images.githubusercontent.com/46509/63188102-6867f380-c015-11e9-8afe-635b604291c5.png)

Animation: http://jonudell.info/h/sidebar-floats-left-in-narrow-window.gif

**Comment by robertknight** [comment]
I was able to reproduce this using the Chrome extension on http://example.com:

<img width="569" alt="Sidebar float left" src="https://user-images.githubusercontent.com/2458/102398421-2bc85580-3fd7-11eb-9b93-5a2dfb1db417.png">

It seemed to happen when the window's width (as given by `window.innerWidth`) went below 600px.

**Comment by lyzadanger** [comment]
This isn't surprising, really, when I think about it. Our responsive layout/breakpoints likely need some attention.

**Comment by lyzadanger** [comment]
It looks like the crux of this problem is an inline style added by `src/annotator/sidebar` in the `show()` method. This inline left-margin value is not updated on window resize. If you collapse and re-show the sidebar, it will no longer "float" because this value will be updated in the inline styles (by the `show` method in the `sidebar` module).
