### ISSUE TITLE
Annotations not getting saved

### ISSUE THREAD

**Issue by anushaharish538** [hypothesis/client#1396]
Hi, 
I have installed the client and h server in my machine and using Nginx to proxify it.
Steps to reproduce
1.Highlight to annotate
2.Add the annotation 
3. Click on "Save"
Expected behavior
The annotation get saved and stays there after the page has been refreshed.
Actual behaviour
Annotatios are disappering afte  page refresh.

**Comment by robertknight** [comment]
If saving the annotation appears to work successfully in the client but the annotation doesn't appear when the page reloads, that suggests that the annotation has not been indexed into Elasticsearch by h. One way to check is to see whether any rows are added to A) the "annotation" table in Postgres and B) the search index in Elasticsearch when the annotation is saved.

I'm going to close this issue since this doesn't sound like a bug in the client, but feel free to continue the discussion here or Hypothesis Open.
