### ISSUE TITLE
Creating annotation fails when selection starts or ends in a link in a PDF

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#1464]
Creating an annotation fails if the selection starts or ends inside a link annotation in a PDF - that is, a link which is contained within the `annotationLayer` element for a given PDF page.

**Steps to reproduce:**

Open http://www.orimi.com/pdf-test.pdf in Via or using the browser extension.

1. Select all the text on the last line of the only page in this PDF, including the URL http://www.education.gov.yk.ca/
2. Click the `Highlight` or `Annotate` button 

**Expected result** 

The selected text is highlighted and a new highlight appears in the "Annotations" tab in the client

**Actual result** 

A JS error occurs and no highlight appears
![Screen Shot 2019-10-28 at 4 22 38 PM](https://user-images.githubusercontent.com/3939074/67725322-2eb15280-f99f-11e9-8fb5-17fe9b9a081a.png)

Related to https://github.com/hypothesis/client/issues/1329

**Notes**

A PDF.js page has several layers: A `<canvas>` containing the visible content, a div containing invisible text (`textLayer`) and a div containing external links and possibly other annotations (`annotationLayer`). Our PDF anchoring code currently expects the selection to contain hidden text from the `textLayer` div but on pages with annotations the selection can end up starting or ending in the `annotationLayer`. Hypothesis functionality aside, this DOM structure causes problems when trying to select text in the PDF because links occur after all the text on the page rather than being part of the text flow as they would be on a normal web page.

**Comment by robertknight** [comment]
It looks like the problem here relates not to the selection of the last word in the page but the fact that the selection ends in a link which is in the `annotationLayer` div in the PDF page rather than the `textLayer`:

<img width="969" alt="Annotation layer link" src="https://user-images.githubusercontent.com/2458/99436873-8ce20800-2909-11eb-9121-c3f3db405541.png">

The same issue causes unexpected behavior if you try to select the last line of this paragraph in the http://localhost:3000/pdf/budlong document in the client's dev server:

<img width="843" alt="Screenshot 2020-11-17 at 19 20 26" src="https://user-images.githubusercontent.com/2458/99437191-0a0d7d00-290a-11eb-9f7c-6825f9a584cb.png">

I've tried to select the text "Budlong Woods ... community area" but because of the DOM structure this ended up selecting the text "Early history" as well. If you try to create an annotation from this selection it will fail.
