### ISSUE TITLE
Realtime updates don't work when sidebar opens on boot

### ISSUE THREAD

**Issue by chdorner** [hypothesis/client#193]
### Steps to reproduce
1. In an incognito tab (you have to be logged-out), open the web inspector with the network tab in your browser
2. Click on the "WS" (websockets) tab
3. Go to `https://hypothes.is/docs/help`
4. Observe that even though the sidebar opens, there is no websocket connection being opened
5. Close the sidebar
6. Open the sidebar
7. Observe that now the client does open a websocket connection

### Expected behaviour
Websocket connections should be created when the client is configured to open the sidebar on boot.

### Actual behaviour
It doesn't. Which is the same behaviour as when the sidebar is not opened on boot, where the websocket connection only gets initialized once the user interacts with the sidebar (e.g. opens it).

### Browser/system information
Probably all of them.

**Comment by nickstenning** [comment]
I will just note that this behaviour was originally introduced in order to avoid opening gajillions of passive websocket connections from sites which embed Hypothesis but where users don't actually interact with the sidebar.

As such, it would be good if opening the connection to the websocket were at least still conditional on some kind of user interaction with Hypothesis, even when the `openSidebar` config option is in use.

**Comment by robertknight** [comment]
I retested the steps from the original issue with the latest client and it no longer reproduces. The logic that connects to the WebSocket on startup was rewritten in a way that fixes this issue: https://github.com/hypothesis/client/blob/e8488b43a71ff2c97a19a69c45ee57ea1582f975/src/sidebar/components/sidebar-view.js#L126.
