### ISSUE TITLE
The tag doesn't work in the newest client (both chrome extension or in web page)

### ISSUE THREAD

**Issue by dmks** [hypothesis/client#1954]
### Steps to reproduce
Post an annotation with tags

### Expected behaviour
The tag should be either autocompleted or created

### Actual behaviour
Nothing happen, see the screenshot.

### Browser/system information
Chrome Version 80.0.3987.116 (Official Build) (64-bit)
MacOS 10.15.2

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/36324/77368273-1c063400-6d19-11ea-8d07-c61cdd3b4636.gif)

**Comment by judell** [comment]
The tag editor has been rewritten, and requires you to press Enter to create a tag. There's a ticket to bring back the old behavior: https://github.com/hypothesis/client/issues/1736 is the issue to track.

**Comment by robertknight** [comment]
#1736 sounds different to me. That issue is worded as being specifically about automatically creating tags when using the tab key to move focus away from the tag input field. What is shown here is automatically creating a tag from any pending input in the editor when clicking "Post to ...". Depending on how #1736 is implemented, it might also resolve this request, but I think we should call it out as a separate requirement.

**Comment by LMS007** [comment]
See https://github.com/hypothesis/client/issues/1954 for more details

**Comment by lyzadanger** [comment]
This has been fixed by https://github.com/hypothesis/client/pull/2503
