### ISSUE TITLE
Merge coercions into paramWhiteList

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#1968]
We could clean up this file a bit and make the paramWhiteList more complete by making it an object whose keys are allowed parameters and values are coercion functions or validation functions.

Perhaps we also need both. 1. coerce then 2. validate.

For example. `"true"` may need to be `true` down stream, but `"true"` is not necessarily invalid.
So a coerce first, then validation check second would make sense.

We ideally should coerce / validate every config value coming in.

**Comment by robertknight** [comment]
The original context around this issue has been lost, so I'm going to close it.

I will add some context for future reference:

- Via needs to support being passed configuration which is then relayed to the client. This is done by passing query params to Via, with a special `via.` prefix, which then get mapped to client configuration in JSON format
- The developer working on Via didn't want that service to have to know about the types of different client configuration values, instead the idea was that Via could just always pass configuration values as strings.
- Hence we added code in the client to coerce string representations of values to the expected types

The downside of this is all the usual problems that can occur when APIs accept stringly-typed inputs.

Personally I would much rather than we change Via so that either it does know about the types of client config values, or the data is passed to Via in such a way that the type info is included.
