### ISSUE TITLE
Groups can no longer be removed from scope control

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#203]
### Steps to reproduce
1. Open client
2. Pull down scope control
3. Click [x] to remove group from view

### Expected behaviour
Group should be removed from view

### Actual behaviour
Nothing happens.

### Browser/system information
Chrome / up to date.

**Comment by robertknight** [comment]
I can confirm using a dev install. The client is making the expected `POST /groups/<pubid>/leave` request but the service is responding with a 404.

The client is sending the expected cookies and `X-CSRF-Token` headers that are used to authenticate this endpoint.

**Comment by robertknight** [comment]
Looks like this was removed in https://github.com/hypothesis/h/commit/eb0baaa39721e9aef7c88ce6225284486fb3633b without realizing who uses it. CC @chdorner

**Comment by chdorner** [comment]
Uhm, the client was using that endpoint and using cookie authentication? Wow...

We might want to revert this commit for now, but we really need to add a big "FIXME", because the client should use a proper API endpoint under the API namespace, and not an endpoint that looks like it's only used by `h`.

**Comment by chdorner** [comment]
Deployed to production. Sorry for the troubles, we've just reverted a change we did earlier, but we'll have to look at properly fixing it in the future.
