### ISSUE TITLE
Provide alternative to `title` attribute for button labels

### ISSUE THREAD

**Issue by klemay** [hypothesis/client#2056]
To meet WCAG 2.0 Criterion 4.1.2 (Name, Role, Value) our buttons need accessible labels. Currently we label them with a "title" attribute, but this attribute is not well supported by assistive technologies and its use for accessibility purposes is generally discouraged. It can still be used for other purposes, such as its hover behaviour, however controls still require an accessible label, such as an aria-label.

**Comment by robertknight** [comment]
> Currently we label them with a "title" attribute, but this attribute is not well supported by assistive technologies and its use for accessibility purposes is generally discouraged.

Do we know some examples of assistive technologies are being referred to here? I saw this advice in a few blogs on the web but mostly those dating back many years ago and was unsure if it was current in 2020. I was not able to see issues with our current use of `title` when testing with VoiceOver on macOS or iOS. I haven't tested NVDA or Jaws myself though.

**Comment by klemay** [comment]
My understanding is that NVDA and JAWS are the most widely used screen readers, with VoiceOver taking an increasingly large share of that. (I'm basing that based on [WebAIM's survey from late 2019](https://webaim.org/projects/screenreadersurvey8/#used)). So if it's not a problem in VoiceOver, we would really need to be sure it's also not a problem for NVDA and JAWS.

**Comment by lyzadanger** [comment]
@robertknight To tick the box here...are you OK with me simply duplicating `title` to `aria-label` on our buttons for now?

**Comment by robertknight** [comment]
> Currently we label them with a "title" attribute, but this attribute is not well supported by assistive technologies and its use for accessibility purposes is generally discouraged.

I wanted to find specific pointers to specs for this.

https://www.w3.org/TR/wai-aria-practices/#naming_with_fallback ([current draft](https://www.w3.org/TR/wai-aria-practices-1.2/#naming_with_aria-label)) seems to be the canonical reference. It is clear that `aria-label` is preferred over `title` as a way to label controls which don't have visible text.

> @robertknight To tick the box here...are you OK with me simply duplicating title to aria-label on our buttons for now?

In the case where the button has visible text, it seems we would usually want to avoid `aria-label` in most cases. Unlike `title`, the `aria-label` will override rather than augment the visible text. I wonder if there are any cases except for the More/Less buttons where we _do_ want to have a title as well visible text?
