### ISSUE TITLE
Add toast message notifying of IE11 deprecation

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#2179]
Add a toast message to the sidebar with some messaging about planned end of support for IE11. This message should only display in affected browsers.

Part of #2043

**Comment by robertknight** [comment]
We previously agreed June 1st as a date to announce in Slack. This is only 13 days away. Since we don't have a pressing need to make any changes which would stop the client working in IE 11 on that date,  I'd suggest that we can make it July 1st instead. FWIW this would coincidentally match [LinkedIn](https://www.linkedin.com/help/linkedin/answer/4135/supported-internet-browsers-for-linkedin?lang=en).

I would propose the text would be something like: _"Hypothesis will no longer support this browser (Internet Explorer 11) after July 1st 2020. See [Link] for more information."_ where [Link] is a link to a knowledge base article that recommends "a modern browser such as a recent version of Chrome, Firefox, Edge or Safari" (or something along those lines).

@klemay or @mkdir-washington-edu would you be able to help with creating or updating our browser support documentation?

**Comment by klemay** [comment]
I'll work with Michael to get a KB article published re: supported browsers and we will post the link here. 

The language looks good; I might swap out [Link] with [our help article on supported browsers](link to kb article)

**Comment by lyzadanger** [comment]
Caveat that at present there isn't support in our toast message for links (i.e. HTML). This is foer the most part intentional, as the messages are not meant to be interactive.

I'm wondering if this message might work better as a sidebar panel instead, with an explicit "dismiss/close/OK" button.

**Comment by lyzadanger** [comment]
@klemay or @mkdir-washington-edu Do either of you have a URL to the Knowledge Base article to which this should be linked? Thanks!

**Comment by klemay** [comment]
@lyzadanger the KB link is: https://web.hypothes.is/help/which-browsers-are-supported-by-hypothesis/

**Comment by lyzadanger** [comment]
Done via #2208
