### ISSUE TITLE
Replying to annotations causes the browser to lose focus of the original annotation

### ISSUE THREAD

**Issue by JonathanReeve** [hypothesis/client#2324]
I'm using Hypothes.is in my course, and we're annotating a text together. There are lots of annotations there. But when I try to reply to one of them, using either Chromium-based browser or Firefox, pressing reply makes me lose focus with the annotation I'm trying to reply to. I can manage to reply, finally, if I can find the original annotation, and try to press reply again—it works the second time, just not the first. 

### Steps to reproduce
1. Press 'reply' to any annotation on [my edition of the Moonstone](https://icla2020.jonreeve.com/texts/moonstone.html) with embedded Hypothes.is layer. 
2. Notice that somehow the focus is stolen, and the original comment you're trying to reply to is buried somewhere else.

### Expected behaviour
I expect to press the reply button and have it open a text area for replying. 

### Actual behaviour
I press the reply button and it doesn't take me to a text area for replying, but somewhere else entirely. 

### Browser/system information
I'm using the latest version of Firefox on Linux. I've also tested this with Chromium.

**Comment by JonathanReeve** [comment]
Ok, I'm starting to understand this one. So when I click on a single annotation, the sidebar narrows the focus to just that annotation. But when I press reply, that focus expands to show all the annotations for the page. So the reply area has in fact opened, but it's just buried deep down in the list of annotations somewhere. 

I guess the thing to do here would be to ensure that clicking reply doesn't automatically widen the focus to all annotations?

**Comment by lyzadanger** [comment]
@JonathanReeve Thanks for your feedback! We also agreed that this behavior is confusing, and have implemented a change that will make this less abrupt. This will deploy shortly to our embedded client (used in LMS contexts), and will be available in the extension after our next release (likely sometime in the next week).

Before the change, if you "selected" one or more annotations in the page and then clicked/tapped the "reply" button, you'd lose the selection and the entire thread tree of annotations would open back up again, like this:

![before-selection-reply](https://user-images.githubusercontent.com/439947/90039253-63736980-dc94-11ea-933b-09d9c1651510.gif)

After these changes, when you click/tap on "reply", the selection will be maintained, and an edit area for your new reply will be visible:

![after-selection-reply](https://user-images.githubusercontent.com/439947/90039284-6b330e00-dc94-11ea-9541-43b338486533.gif)

There is much more detail about this here: https://github.com/hypothesis/client/pull/2434

Fixed by #2437

**Comment by JonathanReeve** [comment]
Great, thanks!
