### ISSUE TITLE
Annotation & Highlight differentiation issue.

### ISSUE THREAD

**Issue by anujpachawadkar** [hypothesis/client#2326]
### Steps to reproduce
1. Open any document(HTML page) from internet that you want to annotate.
2. Turn on the Hypothesis extension/bookmark-let of your browser.
3. **Highlight any sentence** from it.
4. Now **annotate a word** from that Highlighted sentence.
5. Now **refresh the page** & see the line you had highlighted.

### Expected behaviour
Ideally after refresh also, we should be able to see both the entities(Highlight & Annotation) in different color/shades as they were when they had been created.

### Actual behaviour
Whole highlighted line/sentence is darker.

### Browser/system information
**Browser**: Chrome, Firefox (with latest versions)
**OS**: Windows 10

### Additional details
**Annotated Page URL**: https://via.hypothes.is/https://h.readthedocs.io/projects/client/en/latest/developers/envvars/
![Highlight](https://user-images.githubusercontent.com/43320489/87159947-c06bb080-c2df-11ea-8644-e2121dabb033.PNG)
![After annotation](https://user-images.githubusercontent.com/43320489/87159962-c5c8fb00-c2df-11ea-8334-45729ea43564.PNG)
![After refresh](https://user-images.githubusercontent.com/43320489/87159971-c95c8200-c2df-11ea-9479-1a5c1ff9971d.PNG)

**Comment by anujpachawadkar** [comment]
Hi,

I would like to mention here that when I replaced a code of **"highlightRange"** function in **"highlighter.js"** file. This code was from older code version as following:
[**Note**: Ofcourse I converted the code from coffee to JS]

`  white = /^\s*$/

  hl = $("<hypothesis-highlight class='#{cssClass}'></hypothesis-highlight>")

  nodes = $(normedRange.textNodes()).filter((i) -> not white.test @nodeValue)

  return nodes.wrap(hl).parent().toArray()`

So there's might be an issue with the new code/"highlightRange" function implementation.

**Comment by robertknight** [comment]
I couldn't make sense of the [this comment](https://github.com/hypothesis/client/issues/2326#issuecomment-659186667) but I was able to reproduce the issue on the URL mentioned.

The fundamental issue here has always existed as far as I know and it relates to the fact that annotations are first located in the page and then, after the annotations are located, the DOM `Range`s are highlighted. The act of inserting highlights for one annotation modifies the DOM and this can have the effect of invalidating or modifying the `Range`s for other annotations that were created as part of locating the annotations in the page. However it is possible that recent changes to highlighting may change the exact circumstances in which the problem manifests.

One observation I noticed is that whether or not the issue happens depends on the order in which annotations are created. If I create the inner annotation first and then the outer annotation, the problem does not occur. If I create the annotations in the opposite order this avoids the problem. 

The fix for this fundamental problem will I think involve changing the way the locations of annotations within the page are represented before highlighting so that the act of inserting highlights doesn't invalidate them. A potentially smaller + easier improvement might involve sorting annotations by ascending quote length before inserting highlights so that, when one annotation surrounds another, the "inner" annotation gets highlighted first.

**Comment by anujpachawadkar** [comment]
Hi @robertknight,

Yes, I was saying that problem went away when using a new version of the client code but replacing the current highlightRange version with a version based on an older commit and the commit ID is **"d8191a1965"**.
