### ISSUE TITLE
Multiple unrelated Hypothesis frames on one page causes havoc

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/client#249]
_Originally reported as https://github.com/hypothesis/h/issues/3433 by me._

### Steps to reproduce

Create an HTML document with multiple frames, each containing an instance of Hypothesis. The frames must all be hosted on the same origin.

For example:

##### `index.html`

```html
<!doctype html>

<iframe src="/a.html" style="width:45%;height:500px"></iframe>
<iframe src="/b.html" style="width:45%;height:500px"></iframe>
```

##### `a.html` and `b.html`

```html
<!doctype html>

<script async src="https://hypothes.is/embed.js"></script>

<p>
Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula
eget dolor? Aenean massa? Cum sociis natoque penatibus et magnis dis parturient
montes, nascetur ridiculus mus; Donec quam felis, ultricies nec, pellentesque
eu, pretium quis, sem!
</p>
```

### Expected behaviour

Each independent Hypothesis instance can be used on its own without interfering with the others.

### Actual behaviour

The "magic" autodiscovery features cause complete havoc. Specifically:

- frames disagree on who is the "host" and who is the "guest" causing ["A second Discovery server has been detected"](https://app.getsentry.com/hypothesis/prod-client/issues/120271030/) errors.
- frames which contain different documents receive page metadata from the other frames and end up loading the wrong annotations
- messages bounce endlessly between frames causing problems similar to that described in hypothesis/h#2829.
- creating an annotation results in annotation editors being displayed in both sidebar applications.

**Comment by judell** [comment]
Today I was working on an integration that uses the standalone viewer, e.g. https://hypothes.is/a/6aknRpHFEeeBWE9crsbjQA, in a iframe on a page that already has an active instance of H. 

(Why? Because that view is a useful embeddable widget that can enable display of, and interaction with, a individual annotation and its replies.)

As in other scenarios this one triggers "A second Discovery server has been detected" . For this particular use case, since the embedded stream has no concept of, nor need for, a guest/host relationship, it seems possible, and maybe appropriate/useful to return from startDiscovery if document.location.href starts with `SERVICE_URL/a'.

**Comment by robertknight** [comment]
I started putting together a prototype a while back to explore how to simplify the way the sidebar and content frames discover each other. It can be found at https://github.com/hypothesis/client/tree/new-discovery-prototype/discovery-prototype.

**Comment by klemay** [comment]
adding to backlog in favor of https://github.com/hypothesis/client/issues/187

**Comment by robertknight** [comment]
This was fixed initially by https://github.com/hypothesis/client/pull/3599 and then https://github.com/hypothesis/client/pull/3611 replaced the whole mechanism that is used by frames to discover each other. See also ongoing work in https://github.com/hypothesis/client/issues/3533.

In the client's development server there is a manual test page for this at http://localhost:3000/document/multi-frames.
