### ISSUE TITLE
Tapping on page content doesn't auto-close sidebar

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/client#252]
_Originally reported as https://github.com/hypothesis/h/issues/3398 by me._

### Steps to reproduce
1. Visit an annotated page in Mobile Safari on iOS
2. Open the sidebar
3. Tap (anywhere) on the content, outside the sidebar.
### Expected behaviour

The sidebar should close.
### Actual behaviour

The sidebar remains open. If you want to close it you need to tap on the "close" arrow button.
### Browser/system information

Mobile Safari, iOS 9.2?

This issue was split out from #2811.

**Comment by sean-roberts** [comment]
This is the old cursor optimization issue with mobile. Mobile OSs don't register any of the click events unless the element has `cursor: 'pointer'` specified in CSS. Anchors and buttons natively have this but everything else does not.

The two ways you can solve this problem is 
- add `touchstart` event listening to sidebar.coffee in addition to the `click` listening
- add `* {cursor: pointer}` to css if the user agent (the browser definition) is a iProduct

I would go with touchstart as it's the easiest/cleanest.

**Comment by robertknight** [comment]
> Mobile OSs don't register any of the click events unless the element has cursor: 'pointer' specified in CSS. 

 I didn't know about 'cursor: pointer` as a work-around. https://developer.mozilla.org/en/docs/Web/Events/click#Safari_Mobile mentions that adding a no-op `onclick` handler to the element or its ancestors (except `<body>`) should also work. I prefer the suggestion involving adding a `touchstart` event listener though.
