### ISSUE TITLE
Consolidate/refactor `frameSync` and `bridge` services

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#2749]
Right now, there isn't a clarity of responsibility in the `bridge` and `frameSync` services. `frameSync` contains some methods that wrap `bridge` events, but components also use `bridge` directly in other cases (with no wrapping).

An abortive attempt was made to remove `bridge`-wrapping methods from `frameSync` and make components always use (inject) `bridge`, but that doesn't seem quite right and led to some duplicated code.

@robertknight suggested perhaps an `annotator` service, which seems plausible: this service would be responsible for sending and receiving events/messages between the sidebar and the annotator. That seems more intuitive than the setup we have now. In any case, it would be nice to separate out the plumbing- and init-type responsibilities (e.g. `frameSync.connect`) from the communication needs that the components have.

**Comment by robertknight** [comment]
The `bridge` service was removed as part of a refactoring of how different client frames discover each other. The `bridge` was a layer on top of the `frame-rpc` module (now replaced by `PortRPC`) that added the ability to broadcast a message from one frame (eg. the sidebar) to many other frames at once. It turns out that for most messages we want to send them to a specific frame, and for the remainder, this is easily done by a utility that loops over the `PortRPC` connections.
