### ISSUE TITLE
Adder styles sometimes fail to load

### ISSUE THREAD

**Issue by esanzgar** [hypothesis/client#2752]
(_Update (2020-11-21): The issue is sporadic. The steps below may take several attempts to reproduce the issue - @robertknight_)

### Steps to reproduce
1. activate the browser-extension
2. go to https://www.espn.com/
3. after display the sidebar annotate something on the page

### Expected behaviour

Adder should displayed with styles.

### Actual behaviour

Adder is displayed without styles

### Additional details

* This page has a lot of ads and takes a very long time to fully load.

* After steps 1-3, if the browser-extension is disabled and re-enabled the adder shows correct styles.

![Untitled](https://user-images.githubusercontent.com/8555781/98803735-80474680-2415-11eb-9265-4978e58eecbe.gif)

The above two hints indicate that the issue is caused by the slow loading of the page.

**Comment by robertknight** [comment]
I encountered this a few times today on different websites. I had a quick look. The problem seems to be that sometimes the stylesheet is missing from `document.styleSheets` when [this code runs](https://github.com/hypothesis/client/blob/9954de93319b8e4bf3fc3d5268bce4e358a40b39/src/annotator/util/shadow-root.js#L5). My guess is that stylesheets are added to this list after they are parsed and this is not guaranteed to complete by the time that code runs. An alternative would be to get the stylesheet URL from the `<link>` element instead, which definitely will be present in the DOM when that code runs.
