### ISSUE TITLE
SPIKE: consolidate react apps running on the host page

### ISSUE THREAD

**Issue by esanzgar** [hypothesis/client#2981]
There are several react applications running on the host page that could be unified under a common root. This could lead to a simplification of communication between those apps.

@robertknight  suggested trying this step by step.

**Comment by robertknight** [comment]
I don't think this issue is well specified enough to be useful to future developers. What is meant here is that the sidebar container contains multiple components (bucket bar, toolbar) which each render their own Preact roots. What I think we originally discussed was potentially combining these into a single Preact component.

**Comment by robertknight** [comment]
As noted in the previous comment, we might want to make the _sidebar_ one single Preact root, but there are no plans to force all components to be a single Preact root.
