### ISSUE TITLE
Do not link to document or style timestamp as link in Notebook annotation cards IN LMS CONTEXT

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#3098]
A couple of tweaks are needed to annotation metadata as rendered on cards so as to not deeply confuse our early Notebook users when the Notebook is opened in the LMS context.

![image](https://user-images.githubusercontent.com/439947/109979724-32f52a80-7ccd-11eb-86a5-9bf597c87d8b.png)

* The document ("The h documentation" here) should not be linked in the Notebook view. This is most critical here as clicking on it leads to immediate game over. It makes _sense_ that this would be the case, given that the document is not accessible directly and we don't have history/navigation support in the Notebook yet.
![image](https://user-images.githubusercontent.com/439947/109979834-54eead00-7ccd-11eb-943a-c8e9eff21d57.png)
* The timestamp is (correctly) not linked, but it is styled as a link on hover. This should not be styled as a link when it is not:
![image](https://user-images.githubusercontent.com/439947/109980077-88c9d280-7ccd-11eb-9031-978f977070c6.png)

**Comment by robertknight** [comment]
> The document ("The h documentation" here) should not be linked in the Notebook view.

Isn't the change here just that the bouncer link needs to open in a new tab? I think reason you are seeing an error when you click it might be because you don't have bouncer running locally? In production these links in the notebook work, but they load the document inside the iframe instead of a new tab.

> The timestamp is (correctly) not linked, but it is styled as a link on hover. 

I'd suggest that the timestamp should work the same as it does in the sidebar, but again it just needs to open a new tab rather than in the notebook view itself.

**Comment by lyzadanger** [comment]
> Isn't the change here just that the bouncer link needs to open in a new tab? I think reason you are seeing an error when you click it might be because you don't have bouncer running locally? In production these links in the notebook work, but they load the document inside the iframe instead of a new tab.

No. This is a link to the underlying document. Many (all?) LMS documents are not available outside of their LMS contexts.
