### ISSUE TITLE
Compatibility minbrowser.org

### ISSUE THREAD

**Issue by blackgwe** [hypothesis/client#3218]
### Steps to reproduce
1. Download and install https://minbrowser.org
2. login into https://hypothes.is/
3. "Visit annotations in context" of an annotation

### Expected behaviour
<img width="245" alt="Bildschirmfoto 2021-03-29 um 18 37 43" src="https://user-images.githubusercontent.com/6592155/112869871-e9c2ab80-90bd-11eb-87f3-9242f5424928.png">

### Actual behaviour
After pressing "Login" button:
<img width="490" alt="Bildschirmfoto 2021-03-29 um 18 36 53" src="https://user-images.githubusercontent.com/6592155/112869920-f8a95e00-90bd-11eb-85bb-c43191ff6608.png">

### Browser/system information
* Min Browser https://minbrowser.org
* Version 1.18.1
* MacOs (I think, the os does not matter)

### Additional details
Min is written entirely with CSS and JavaScript using [Electron](https://www.electronjs.org/), and is open-source software, [available on GitHub](https://github.com/minbrowser/min).

**Comment by robertknight** [comment]
Thanks for the report. The Hypothesis client's login process involves a popup window. According to https://github.com/minbrowser/min/issues/140 this browser does not support this and that affects login on a number of other websites. For security reasons we're unlikely to change the popup requirement, so the issue will need to be fixed in Min. Once https://github.com/minbrowser/min/issues/140 is resolved, the client may work with it.

**Comment by blackgwe** [comment]
Thank you very much!
