### ISSUE TITLE
Deleting annotations doesn't work on Chrome 91.0

### ISSUE THREAD

**Issue by esanzgar** [hypothesis/client#3254]
On Chrome version >= 91.0 the delete button on an annotation card doesn't work:

![image](https://user-images.githubusercontent.com/8555781/113701508-885f9580-96d8-11eb-9389-da7289303914.png)

We believe this is related to a security feature that could prevent third party iframes to use window.confirm.

### Steps to reproduce
1. Click on the delete button

### Expected behaviour
A pop-up dialog should appear to confirm the deletion. 

### Actual behaviour
The pop-up dialog doesn't appear.

### Browser/system information
Chrome >= 91.0

### Additional details
Latest versions of Safari and Firefox work correctly.

**Comment by lyzadanger** [comment]
If this is indeed a `window.confirm` restriction, we'll also need to address the other usage, which is in the `HypothesisApp` component to warn of unsaved draft annotations.

**Comment by lyzadanger** [comment]
More information on the "intent to remove": https://groups.google.com/a/chromium.org/g/blink-dev/c/hTOXiBj3D6A/m/YdExd4wgAgAJ?pli=1

**Comment by robertknight** [comment]
It looks like this change is coming to Safari and Firefox in future as well. See https://github.com/whatwg/html/pull/6297 that was linked from the above blink-dev mailing list thread.

**Comment by robertknight** [comment]
The issue has been fixed for users of Chrome >= 91, and any other browsers where this issue occurs, in https://github.com/hypothesis/client/pull/3274. Users of other browsers will still see the native confirmation dialog while we polish the styling of the new one, then we'll flip the switch and use it everywhere.

I'm closing this issue since the main issue here has been resolved, although there is follow-up work ongoing.
