### ISSUE TITLE
Q: why don't you accept feature-requests here?

### ISSUE THREAD

**Issue by ankostis** [hypothesis/client#4057]
It's unusual for an open source pretty to restrict the issues ticketing system (GitHub) to bugs-only.  As directed by [the new-issue template](https://github.com/hypothesis/client/blob/master/.github/ISSUE_TEMPLATE.md), RFEs must be submitted through the google mail list:

```
1. Only report **bugs** with the Hypothesis client here. If you want to discuss
   potential new features, please use our developer mailing list:

       https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev
```

Mailig lists are not use-friendly for such requests, since they do not facilitate comments on the code, branches or other software constructs.

Would you reconsider this decision?

**Comment by robertknight** [comment]
This template was written several years ago. GitHub and Hypothesis have changed a lot since. I think we should revise it. 

The parts of that template that are still valid are:

- Email support@hypothes.is if you need support (eg. with your account, a paid Hypothesis service or something else)
- The development mailing list still exists for people who prefer to use that

One reason why we might still want to direct some feature requests elsewhere is that depending on the request, they may span multiple parts of the product (browser client, browser extension, backend etc.).

**Comment by robertknight** [comment]
I have revised the issue template to remove the "only report bugs" text. GitHub now has better tools for us to transfer issues or convert them to [discussions](https://github.com/hypothesis/client/discussions) than it did when the template was written. As such I think we can be more liberal about accepting other kind of feedback here.
