### ISSUE TITLE
In certain PDFs: Selecting text including the last character of a page doesn't allow annotation

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/client#5024]
### Steps to reproduce
Replicated in two assignments:
- https://hypothesis.instructure.com/courses/258/assignments/3732
- https://hypothesis.instructure.com/courses/258/assignments/3733

1. Open assignment
2. Select text in the middle of a page and confirm the Adder appears
3. Select text to include the last character on a page and confirm the Adder does **not** appear.

### Expected behaviour
As long as the text selection doesn't span multiple pages we should be able to annotate.

### Actual behaviour
The Adder doesn't appear and the Page Note icon on the Sidebar doesn't change into the Annotation icon.

### Compare:
<img width="922" alt="image" src="https://user-images.githubusercontent.com/22603275/200068335-58af1661-80ce-4ade-a5dd-ae46a427e354.png">
<img width="886" alt="image" src="https://user-images.githubusercontent.com/22603275/200068363-abe57d2a-866f-43cf-becf-527714ab445f.png">

### Browser/system information
Chrome 107
macOS Big Sur 11.6.5

### Additional details
Discussion - https://hypothes-is.slack.com/archives/C2BLQDKHA/p1667501684238469

**Comment by lyzadanger** [comment]
I've reproduced locally with the specific PDF in question, which I'll upload to this comment for reference. 

[microbiology.pdf](https://github.com/hypothesis/client/files/10114341/microbiology.pdf)

The issue is this: Attempting to select any text leading up to and including the last character on page 177 will not pop up the adder, thus not allowing annotation on it.

While this doesn't appear to be "selecting text across multiple pages" from the user perspective, on a code level, it is seen as such. There is something about this particular range/selection that looks like it's "across pages."

Specifically, `annotator/anchoring/pdf`'s `canDescribe` function returns `false` on ranges that include this text, and if one examines the (handled) exception therein:


```
Error: Selecting across page breaks is not supported
    at getTextLayerForRange (pdf.js:622:11)
    at canDescribe (pdf.js:639:5)
    at PDFIntegration.canAnnotate (pdf.js:206:12)
    at Guest._onSelection (guest.ts:703:28)
    at guest.ts:218:14
    at selection-observer.js:40:9
```

The next thing to try to figure is why this text "seems like" it is across page breaks.

**Comment by lyzadanger** [comment]
@mkdir-washington-edu To help me assess appropriate level of effort for attacking this: do you know of any other PDF documents that exhibit this behavior (last text on a page is non-annotate-able, not the "can't annotate across pages", which is a separate deal), and/or have any other users reported it?

**Comment by mkdir-washington-edu** [comment]
@lyzadanger I've seen this crop up several times before, though I took a look at our most recent tickets (back a few months) that involve PDFs and can't find any example PDFs that have this issue.

I think it's a rare problem. I can make a note to update this issue with PDFs when we see it again.

**Comment by lyzadanger** [comment]
@mkdir-washington-edu Thanks for taking a look! We're still planning on moving forward with a fix on this as the identified underlying cause is a pattern that could affect other documents, and fixing it will make our "text-selection computation" more robust overall.
