### ISSUE TITLE
All annotations orphaned for no obvious reason

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#527]
### Steps to reproduce
1. Go here: https://www.theatlantic.com/magazine/archive/2014/06/the-case-for-reparations/361631/

### Expected behaviour
Annotations should anchor

### Actual behaviour
They aren't

### Browser/system information
Chrome extension

**Comment by fatbusinessman** [comment]
From an initial investigation, I can reproduce this problem some of the time, but not all of the time. There aren’t any JavaScript errors staring out at me from the console, so at a best guess I’d say this is a timing issue based on the length of the article and some number of the tracking/ad scripts on it.

**Comment by robertknight** [comment]
I dug into this today and I think I know what the problem is. It affects pages which contain at least one iframe that is same-origin with the top-level page, triggering the client to try and enable annotation of content in the iframe as well as the top-level document, a capability that EPUBs need.

The support for multiple frames in the sidebar code is incomplete in at least one way. The `frameSync` service tries to trigger loading/anchoring of _all_ annotations in _all_ frames, yet it assumes that it will get a single `sync` response from the host page informing it of whether an annotation anchored or not. So, given the context of eg. a news article with a large iframe on it displaying an advert, what can happen is:

- An annotation is loaded for the URL of the top-level page (the article in this case)
- A `loadAnnotations` message is dispatched to both the top-level page and an ad iframe to ask both frames to anchor the annotation, even though it is clearly not going to be found in the ad iframe
- The annotation anchors successfully in the top-level page but fails to anchor in the ad iframe
- A `sync` message comes back from the top-level page with the `$orphan` flag set to `false`
- A `sync` message comes back from the ad iframe with the `$orphan` flag set to `true`
- The client displays the annotation as an orphan, because that message came back last, even though it did in fact anchor in one of the frames

The ordering in which the "sync" messages come back is not deterministic, which is why it happens only sometimes. Additionally, the set of iframes that a news website load can depend on which adverts are shown which in turn can vary with each payload and by other factors such as the viewer's region and language.

**Comment by robertknight** [comment]
The issue has been worked-around for Hypothesis v1.40 by limiting iframe support to those which explicitly opt in. The underlying issue still exists and I'm going to file a separate issue for that.
