### ISSUE TITLE
Cross-format annotations failing to anchor on PDFs

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#558]
### Steps to reproduce
1. Go to this annotation https://hyp.is/tQQmNrUPEeeITl9qhC6BCQ/journals.plos.org/plosone/article?id=10.1371/journal.pone.0183175

### Expected behaviour
It should anchor

### Actual behaviour
It orphans. 

### Browser/system information
Chrome extension

### Additional details
Original annotation was made on this page: http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0183175
Direct link: https://hyp.is/tQQmNrUPEeeITl9qhC6BCQ/journals.plos.org/plosone/article?id=10.1371/journal.pone.0183175

Other cross-format annotations succeed at anchoring on PLOS ONE, so the problem is intermittent.

**Comment by robertknight** [comment]
Debugging the problem using Hypothesis v1.48, the anchoring process is failing with this exception:

```
Error: Invalid page request
    at WorkerTransport_getPage [as getPage] (pdf.js:2880)
    at PDFDocumentProxy_getPage [as getPage] (pdf.js:2050)
    at PDFViewer.getPageTextContent (viewer.js:5242)
    at getPageTextContent (injector.bundle.js?4caca7:formatted:4079)
    at t (injector.bundle.js?4caca7:formatted:4106)
    at <anonymous>
```

The `pageNumber` argument is 11, but the document only has 10 pages! How could that have happened?

There are a couple of suspicious places in `pdf.coffee` which call `getPageTextContent` with potentially invalid indexes: [getPageOffset](https://github.com/hypothesis/client/blob/4d05b4266352ce2b9cbd8b0933604296c95bf1fd/src/annotator/anchoring/pdf.coffee#L54) and [findPage](https://github.com/hypothesis/client/blob/4d05b4266352ce2b9cbd8b0933604296c95bf1fd/src/annotator/anchoring/pdf.coffee#L106). The `findPage` function is in turn used from `priortizePages` which is used to generate a list of page indexes to search for quotes, using the position anchor to preference pages "nearer" to the likely location of the quote.

A problem here is that the position anchor comes from the HTML version of the document, which includes text that is not present in the PDF version. My guess is that the position anchor start offset is a value which is beyond the end of the text of the PDF version.

**Comment by robertknight** [comment]
This patch fixed anchoring of one of the two annotations (https://hyp.is/tQQmNrUPEeeITl9qhC6BCQ/journals.plos.org/plosone/article?id=10.1371/journal.pone.0183175):

```diff
diff --git a/src/annotator/anchoring/pdf.coffee b/src/annotator/anchoring/pdf.coffee
index 20350b65..bef28b99 100644
--- a/src/annotator/anchoring/pdf.coffee
+++ b/src/annotator/anchoring/pdf.coffee
@@ -97,7 +97,8 @@ findPage = (offset) ->
   #    150    | 2
   #
   count = (textContent) ->
-    if total + textContent.length > offset
+    lastIndex = PDFViewerApplication.pdfDocument.numPages - 1
+    if total + textContent.length > offset or index == lastIndex
       offset = total
       return Promise.resolve({index, offset, textContent})
```

**Comment by robertknight** [comment]
The second annotation fails with a "Quote not found" error:

```
Error: Quote not found
    at findInPages (injector.bundle.js?21ee77:7918)
    at next (injector.bundle.js?21ee77:7939)
    at <anonymous>
```

Looking at the text extracted from the PDF for the page containing the quote, it is:

"_assumes,weadoptedthemorecommonlyusedReducedMajorAxis(RMA)methodofcorre-lationtodeterminetheslopebetweenthetwovariables(calculatedusingthe™smatr∫softwareroutinefortheRsoftwarepackage)(S3Table).Thissoftwarepackagealsocalculatestheslopeconfidenceinterval(CI).However,wefoundtherewereslightdifferencesbetweenourRMAresultsandthosepublishedbyKilbourneandMakovicky[11],evenwhenweanalyzedtheiroriginaldatawiththeRsoftwarepackage.Consequently,inTables1,3,5and7,wecalculatedallourownresults,ratherthanreprintthenumbersgivenbyKilbourneandMakovicky[11].WefollowedtheconventionsofKilbourneandMakovicky[11]inplottinglengthvs.cir-cumference,whichshouldgiveanisometricslopeinlog_"

As opposed to the stored quote, "_We followed the conventions of Kilbourne and Makovicky [11] in plotting length vs. circumference, which should give an isometric slope in log-log space of approximately 1.0 (linear dimension vs. linear dimension)_"

This second issue will require more work to resolve because we'll have to make quote selector resolving more robust to the spacing differences seen here.

**Comment by judell** [comment]
I tried this just now in the current extension and also in Firefox with PDF.js 2. Both annotations anchor in both cases. A bit mysterious because I don't think we've made any relevant changes. However I'm adding this one to the test suite.

**Comment by lyzadanger** [comment]
@dwhly @judell This is anchoring for me with Chrome 85, extension 1.507 — OK to close?

**Comment by robertknight** [comment]
The original URL can no longer be resolved through Via. Visiting it directly returns the HTML version of the page: https://journals.plos.org/plosone/article?id=10.1371%2Fjournal.pone.0183175.

The PDF version of the article has been moved to a different URL which is accessible by clicking the Download PDF link at https://journals.plos.org/plosone/article?id=10.1371%2Fjournal.pone.0183175 (I can't share the PDF URL directly because it is a temporary URL with a signature which expires). Both annotations anchor when that PDF is viewed through the extension.
