### ISSUE TITLE
Direct linking no longer selects the annotation

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#560]
### Steps to reproduce
1. Click this: https://hyp.is/p5kNvriIEeeth1-bZMS47g/psychcentral.com/blog/archives/2011/01/31/are-we-rational-animals/

### Expected behaviour
Annotation should be selected, and the only one showing.

### Actual behaviour
All annotations on the page are visible.

### Browser/system information
Chrome

**Comment by dwhly** [comment]
Ok-- appears to be working now.  SO STRANGE.

**Comment by da70** [comment]
I tried clicking on the link in Chrome 61.0.3163.100.  The first time, no annotations came up in the sidebar, and no annotations were highlighted on the page.  I closed the tab and then loaded the page a minute or two later.  After some delay two annotations showed up in the sidebar and two corresponding highlights were on the page.  Screenshot:

![two annotations visible instead of one](https://user-images.githubusercontent.com/5719179/31953073-3fd43cc6-b8b0-11e7-9eac-b98394feef82.png)

The link in this ticket appears to be for the second annotation?

**Comment by da70** [comment]
I tried again, because I couldn't recall if I'd actually clicked the link on the second attempt or just loaded the redirected-to page.
I clicked on the link twice and got the same result, which I presume is the correct one: one annotation in the sidebar, and 2 highlights on page, the page scrolled initially to the first highlight, then the second, which flashed blue then turned yellow:

![hypothesis-client-560-2](https://user-images.githubusercontent.com/5719179/31953990-5c508ccc-b8b2-11e7-94a4-0dbef6d43640.png)

The initial problem in the previous comment with no annotations loading perhaps was the result of network latency or some other race condition.
