### ISSUE TITLE
Controls to limit export to a specific user

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#5775]
We need to allow users to limit the annotations they export to "my" annotations, another specific users, or to everyone.  We'll develop a fuller description and some UX as this issue develops;

**Comment by jaredpdesigns** [comment]
Here is the revised mocks:

<img width="408" alt="export-revised" src="https://github.com/hypothesis/client/assets/6108048/c7d36a9e-8d71-4ead-a963-b657aa5de09b">

**Notes:**
- Only selected value shows the quantity of annotations to make it clear how many will be exported.
- Dropdown for selecting the user includes the following sections:
  - Me (default selected)
  - All Annotations
  - List of users proceeded by a search input
  - Creating a search will reduce the list of users
  - Selecting one of the options in the dropdown will close the dropdown and update the value of annotations

**Comment by acelaya** [comment]
Can I suggest doing a couple of iterations on this?

1. First we focus on supporting "export my annotations" and "export all annotations".
2. Then we extend it with support to export any user's annotations.

The main reasons are to make sure we have point 1 done this week, and because for point 2 we will need to put some extra work on building the extra UI components.

**Comment by robertknight** [comment]
I would prefer to start by using the existing [Select control](https://patterns.hypothes.is/input-select) from Hypothesis's pattern library, which is what the Import tab uses. As Alejandro noted, this doesn't currently support customizing item appearance or adding complex non-static controls, and that is a fair amount of work to do. In a version using the existing control, the dropdown menu can work the same way as the Import menu, but the first item would be "All users" rather than blank (no user). Pre-selection of the current user would work the same way as in the Import tab.

If we do a custom design for the annotation count and the items, we should look at rolling the same design into the Import tab as well for harmony.

In other words, rather than slicing this work by functionality, it could be done in steps like this:

1. Initial version that uses the same select component as the Import tab
2. Create custom picker with static menu items, supporting customization of static item appearance
3. Add search capabilities to the dropdown

Where step (1) is a known and modest amount of work, and the other steps involve more uncertainty and a lot more iteration. 

For a custom picker, we might be able to leverage some of the work done for the client's existing drop-down menus, but I'm not sure how much. In terms of existing references to look at for accessibility and keyboard interaction, we can use React Spectrum's [Picker](https://react-spectrum.adobe.com/react-spectrum/Picker.html).

**Comment by jaredpdesigns** [comment]
@robertknight @acelaya agree a multi-phased approach makes sense. I figured a custom control was a heavier lift. Also planned for this to support the import control as well.

FWIW was also thinking there would be a threshold for the search showing up of at least 5 or more users.

**Comment by acelaya** [comment]
I'm going to start with phase 1

> 1. Initial version that uses the same select component as the Import tab

**Comment by acelaya** [comment]
Since the main capability described here is already implemented by https://github.com/hypothesis/client/pull/5779, I'm going to close this issue.

The missing UI improvements will be tracked by https://github.com/hypothesis/client/issues/5841
