### ISSUE TITLE
Link to kb articles from export & import

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#5783]
It will help our users to link directly to our kb articles from within our product UX.  We should do this for the import and export functionality.

**Comment by jaredpdesigns** [comment]
@dwhly what do we think of this?

- Provides directions with link for Export. **Note:** here I believe the filename would be pre-filled and user selection would show up when I first open the panel?
- Handles use case for Import with directions _before_ a user has selected a local file. One assumes that we wouldn't have a user selection dropdown or import button until they’ve selected a file. We could hide the text if they have selected a file?

<img width="832" alt="export-import-helper-text" src="https://github.com/hypothesis/client/assets/6108048/a84faccf-b062-4d1c-a701-b54c0caf260d">

**Comment by acelaya** [comment]
Should we display this helper text statically, or only when the sidebar is loaded in the context of the LMS?

**Comment by robertknight** [comment]
Some thoughts:

- We've seen that users are very prone to not reading long text in the UI, so we should try to keep UI text concise. I was thinking of something like `[Learn more] about copying and exporting annotations`, where "Learn more" is a KB link.
- Another reason to keep UI text concise is that it will get longer when translated to other languages.
- The Hypothesis client has to avoid using education-specific terms like "assignment" or "course" outside the LMS. We _can_ change the wording to suit the context if absolutely needed, but so far we have avoided this.

Above all though, we should try to find a way to do wider user testing of this feature. Last week internally quite a lot of concern was raised about users not being able to complete the workflow of copying annotations between courses or groups either because they don't connect Import/Export with copying or because of difficulties using file upload/download for this.

**Comment by acelaya** [comment]
+1 for being concise

**Comment by dwhly** [comment]
Lets move forward with the simple format.

**Comment by jaredpdesigns** [comment]
@robertknight I still think it's a good idea to provide some helper text under `Import` if a user hasn't selected a file, but a concise link to a KB article above the primary input on both feels good:

<img width="832" alt="export-import-helper-text" src="https://github.com/hypothesis/client/assets/6108048/822a41cf-d54c-454d-a158-b4565a93426e">

For clarity here, this helper text would go away if a user selected an appropriate file, which would then parse the file for users and provide the user dropdown and import button:

<img width="408" alt="import-with-progress-1" src="https://github.com/hypothesis/client/assets/6108048/4c70087b-036a-4087-bf3b-68819eca970c">

**Comment by dwhly** [comment]
I'm not sure the helper text should go away when the user selects a file.  Its short, lets just keep it there.

**Comment by robertknight** [comment]
> Personally I think nearly every feature probably needs a kb article and a stable place in the UX to access that article that never disappears.

This could add a lot of noise to the UI if we had such hints everywhere. As I see it, the reason we're adding this here is because there is a significant cognitive step between the feature we provide (Export / import) and the uses cases we're trying to enable (copying annotations between groups, copying annotations from the sidebar into a document), and we think users are more likely to need hints than for other features.

**Comment by robertknight** [comment]
@mkdir-washington-edu - We need URLs for the support articles that the "Learn more" links in Jared's mocks (see https://github.com/hypothesis/client/issues/5783#issuecomment-1710509495) should go to. Do we have a suitable URL already, or could you reserve one?

**Comment by robertknight** [comment]
KB article link is https://web.hypothes.is/help/exporting-and-importing-annotations-in-the-hypothesis-web-app/. Note this is currently hidden from the public while it is being drafted.

Slack thread: https://hypothes-is.slack.com/archives/C2BLQDKHA/p1694177722614069?thread_ts=1694167645.268369&cid=C2BLQDKHA

**Comment by robertknight** [comment]
@mkdir-washington-edu - If I publish a client release that includes the link to https://web.hypothes.is/help/exporting-and-importing-annotations-in-the-hypothesis-web-app/ soon, will we have something that we can show at that URL? It's OK if it is minimal at this point.

**Comment by robertknight** [comment]
The ["Learn more" link](https://github.com/hypothesis/client/issues/5783#issuecomment-1710509495), which is the key part of this, is now shipped. We still need to decide if we want the additional text shown in that screenshot.

My personal preference would be to have a cleaner UI and rely on the user to either be able to understand that the big "Export" tab right next to "Import" is where you go to generate a "Hypothesis _export_ file", or click the "Learn more" link to see a workflow with screenshots. However, it is up to @dwhly to make that call.

**Comment by dwhly** [comment]
@robertknight Clean works fine for now.  Thanks!
@mkdir-washington-edu Can you republish that article w/ the shorter title "Exporting and importing annotations"?  Since that article will be the root for all of our pathways.  Sorry for the change.

**Comment by robertknight** [comment]
OK, I'll close out this issue for now. We can revisit in response to user feedback / observations.

**Comment by mkdir-washington-edu** [comment]
@dwhly I can change the title, but please note that the current URL is the title (which is what our KB software defaults to): https://web.hypothes.is/help/exporting-and-importing-annotations-in-the-hypothesis-web-app/

I think it's better if I make a new URL and with the article at it and get rid of the old URL.

Also, there were Marketing reasons to have different articles for the web app and the LMS app. Have those been resolved?

**Comment by mkdir-washington-edu** [comment]
@robertknight Per Dan's note I updated the URL for this article to https://web.hypothes.is/help/exporting-and-importing-annotations/

**Comment by dwhly** [comment]
> Also, there were Marketing reasons to have different articles for the web app and the LMS app. Have those been resolved?

Nope.
