### ISSUE TITLE
SPIKE: Verify functionality of new NVDA screen reader + firefox (Requires Windows)

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#5924]
Hi,

I know it has been an extremely long time since we last spoke.

It seems that the work to implement accessible selections in Google Chrome completely died. What they did end up implementing was not accurate. And I believe that the person/company who did it, may have ended their contract with Google now.

However, James Teh, in his capacity at Mozilla kindly found some time to implement the IAccessibleTextSelectionContainer interfaces in Mozilla Firefox. And that implementation is now in Mozilla Firefox stable. I am testing with Firefox 118.

So far, the testing I have done with NVDA, it seems to be working great on most websites.

I have a try build of NVDA with this support if you would like to try it out:
https://nvaccesslimited-my.sharepoint.com/:u:/g/personal/mick_nvaccesslimited_onmicrosoft_com/EacBWhdZZWJImkep8ko8OOABRFzcpHmos598gZYPz9ZzLg?e=0av1OO

When running NVDA with Mozilla Firefox, press NVDA+shift+f10 to activate native selection mode. Then as you make a selection in NVDA's browse mode with shift+arrows, the browser's native selection should automatically update at the same time.

One scenario this enables is allowing a user to press control+c to copy rich content from the page, rather than just NVDA's browse mode plain text.

An example page where this works is the NV access home page: https://www.nvaccess.org/

I am able to select any content on the page successfully.

Of course, the particular scenario you will be most interested in is working with Hypothesis - enabled web pages. E.g.: https://via.hypothes.is/https://www.deque.com/blog/axe-con-building-a-large-accessible-conference/

Sadly however, If I visit that page with Mozilla Firefox and NVDA, enable native selection mode in NVDA with NVDA+shift+f10, and then use shift+arrows to make a selection, it doesn't seem that Firefox is making the selection properly. At least, when I then press control+c, it is as if nothing was selected. Also, if I select something, turn off NvDA's quicknav mode, then press a or h to annotate/highlight with Hypothesis, nothing happens either. It is as if either no DOM selections are occurring, or Hypothesis javascript is intercepting the selection and disallowing it / drawing its own fake selection.

Could you please verify that Hypothesis code does not block or manipulate the DOM selection (a part from fetching it to annotate / highlight the position)?

Feel free to test out my NVDA try build. And I'm happy to jump on a call, and or chat with anyone at Hypothesis who can help me better understand / debug this.

Kind regards
Mick

**Comment by robertknight** [comment]
I have done some initial testing today with Mick's build and was able to use it to make a selection in Firefox that Hypothesis was able to see, and then create an annotation from that. I was able to create annotations on the page mentioned at https://via.hypothes.is/https://www.deque.com/blog/axe-con-building-a-large-accessible-conference/. I did encounter situations where the native selection got out of sync with NVDA's selection. So far this appears to happen after creating a selection and then pressing an arrow key. This clears the NVDA selection (like arrow keys do when not using a screen reader) but didn't clear the native selection. This didn't seem like a fatal flaw as the selection was re-synchronized the next time a new NVDA selection was started. 

I also tested in Chrome and was I was able to turn native selection on. However while creating an NVDA selection did select _something_ in the native app selection, but it was out of sync with the NVDA selection, making it useless. Microsoft Edge behaves the same way, which is expected since it is based on Chrome.

**Comment by robertknight** [comment]
The functionality has been verified here. I think what remains is clarifying the path to getting the NVDA changes shipped, so there is an end-to-end working solution for users. See also https://github.com/nvaccess/nvda/issues/5354#issuecomment-1792203675.
