### ISSUE TITLE
realtime update shows wrong display name

### ISSUE THREAD

**Issue by judell** [hypothesis/client#666]
User A has sidebar active on a page.

User B posts an annotation.

User A clicks red arrow to refresh sidebar.

User A's display name appears on the annotation.

After page refresh, user B's display name is shown as expected.

**Comment by dwhly** [comment]
This also happens in the /stream, which might be an easier way to track down the problem.

Repro:
Go to /stream.
Be logged in.
Wait.

What should happen:
You see annotations float by from others.

What does happen:
All new annotations appear to be written by you.

**Comment by ajpeddakotla** [comment]
Possibly linked to this issue? https://github.com/hypothesis/client/issues/666

**Comment by ajpeddakotla** [comment]
After talking with the team - the feedback for this issue is that this is only a bug that is encountered by H team members, as we have the `client_display_name` feature flag enabled. 

H users in the wild are therefore not seeing this behavior. 

So the real question that we need to answer here is if we want the display name feature to ship for users in the wild (eLife users currently have this feature as eLife requested it), and if we do, we'll need to fix this bug before we ship that feature.

**Comment by robertknight** [comment]
This was fixed in https://github.com/hypothesis/h/pull/5595.
