### ISSUE TITLE
Annotations are anchoring but showing under orphans

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#679]
### Steps to reproduce
1. Go here: https://via.hypothes.is/https://www.theguardian.com/technology/2010/jun/20/internet-everything-need-to-know
2. Open sidebar

### Expected behaviour
A bunch of annotations under "Annotations"

### Actual behaviour
A bunch of *anchored* annotations under "Orphans"

### Browser/system information
About this version
Version:
1.71.0
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
URL:
https://www.theguardian.com/technology/2010/jun/20/internet-everything-need-to-know
Username:
dwhly
Date:
21 Feb 2018 10:37:00 -0800

![screen shot 2018-02-21 at 10 34 00 am](https://user-images.githubusercontent.com/1413074/36498467-33e8b440-16f3-11e8-999d-0b0d3cb5523d.png)

**Comment by klemay** [comment]
For what it's worth, I am not able to reproduce:
<img width="1549" alt="screen shot 2018-02-21 at 1 41 15 pm" src="https://user-images.githubusercontent.com/12087705/36498708-1f865862-170d-11e8-9638-a99acd2c611e.png">

**Comment by robertknight** [comment]
I was not able to reproduce either in Via or using the Chrome extension. A possible reason that we might have had different experiences is because we might be seeing different ads or other features on the page and some of those ads might be loading JS which causes anchoring to break.

_If_ someone (perhaps @dwhly) can reproduce the problem with the dev tools open and copy/paste any errors that are reported here that would be useful.

If you cannot reproduce today @dwhly I suggest we close this for now and wait until the issue comes along in a way that can be more widely reproduced.

**Comment by dwhly** [comment]
Works great today, I'll look for another opportunity to break our stuff!
