### ISSUE TITLE
Hypothesis misallocating annotations between parent and child iframe

### ISSUE THREAD

**Issue by felliott** [hypothesis/client#688]
### Steps to reproduce

1. Embed hypothesis in a parent frame and a child frame (assigning a `subFrameIdentifier` in the page config for the child).
2. Make annotations in both frame contexts.
3. Reload the page.

### Expected behaviour

Both the parent frame annotations and the child frame annotations should link to the proper spots in their respective frames.

### Actual behaviour

Annotations for one frame end up orphaned, while the other frame's annotations are linked.  It seems as though the parent frame's annotations are orphaned far more often than the child frame's. Screenshot:

![screen shot 2018-03-08 at 1 42 09 pm](https://user-images.githubusercontent.com/86835/37169832-108d77fc-22d7-11e8-9527-9737398cb1a1.png)

### Browser/system information

*OS:* macOS Sierra 10.12.6
*Browsers:* tested in Firefox 58, Chrome 64, Safari 11.0.3

This is on my local OSF development environment, with modified versions of the OSF (parent frame) and MFR (serves the content of the child frame), and the hypothesis client to add hypothesis and support the single sidebar.

##### osf.io

Added [here](https://github.com/CenterForOpenScience/osf.io/blob/develop/website/templates/project/view_file.mako#L248):

````
    <script type="application/json" class="js-hypothesis-config">
     {"assetRoot": "http://localhost:3001/hypothesis/1.71.0/"}
    </script>
    <script src="https://hypothes.is/embed.js" async></script>
````

##### MFR

Added [here](https://github.com/CenterForOpenScience/modular-file-renderer/blob/develop/mfr/extensions/pdf/templates/viewer.mako#L40):

````
    <script type="application/json" class="js-hypothesis-config">
     {
         "assetRoot": "http://localhost:3001/hypothesis/1.71.0/",
         "subFrameIdentifier": "meow"
     }
    </script>
    <script src="https://hypothes.is/embed.js" async></script>
````

##### hypothes.is client:

Ran locally on `localhost:3001` with [this PR](https://github.com/hypothesis/client/pull/681).

### Additional details

Quoting @robertknight from https://github.com/hypothesis/product-backlog/issues/493#issuecomment-367935217:

> I've realized there is a fundamental issue in src/sidebar/frame-sync.js around handling of multiple frames which is actually not specific to this scenario. In brief, all connected frames will try to anchor all annotations fetched from the API. Depending on what order anchoring results from the correct vs. wrong frames for a particular annotation come back, the annotation will show up as an orphan or not.

**Comment by LMS007** [comment]
@felliott 

Just to be clear, is this use cases when you have hypothesis on your page and your page also has an iframe that points to another page which also has hypothesis? More or less the inception case as demonstrated by this rough screenshot?

![Screen Shot 2020-12-30 at 12 20 37 PM](https://user-images.githubusercontent.com/3939074/103379242-e194a900-4a99-11eb-9888-c14a288aaa3a.png)

I ask because I don't see two sidebars in your original screen shot but the description seems like it is the case.

If that's the case, there likely will be a number of things broken or funkey in both sidebars. RPC requests, anchoring, etc. Perhaps a fix for this might be to figure out a way to deactivate the inner sidebar(s). Having two sidebars working at the same time will lead to some confusing and unpredictable behavoir such as double annotations/highlights. In fact, if the group was different  for each sidebar you would be making an annotations in two different groups at once. None of this makes sense. I think for this case, we need to LOTR approach -- one ring to rule them all.


relates to https://github.com/hypothesis/lms/issues/433

**Comment by robertknight** [comment]
The way annotations are sent to frames has been overhauled as described in https://github.com/hypothesis/client/issues/631#issuecomment-1173865009. Annotations are now sent only to one frame instead of all frames. The matching of annotations to frames is determined by the logic in https://github.com/hypothesis/client/blob/25b22fc6c4b1b1de795ecf69256bc2956d2e9951/src/sidebar/services/frame-sync.js#L52.
