### ISSUE TITLE
Hypothesis logo sometimes doesn't show in groups dropdown

### ISSUE THREAD

**Issue by klemay** [hypothesis/client#962]
### Steps to reproduce
1. Log in to an account that is a member of multiple Hypothesis private groups
2. Go to any web page - for example https://en.wikipedia.org/wiki/Golden_Retriever and activate Hypothesis

### Expected behaviour
Once you're logged in, you should be able to switch to a private group and see it in the groups selector like so:

<img width="482" alt="screen shot 2019-02-19 at 1 52 31 pm" src="https://user-images.githubusercontent.com/12087705/53039659-a1038780-344d-11e9-8ede-6cb59d2cb1e7.png">

### Actual behaviour
For some private groups, the Hypothesis logo doesn't show up:
<img width="477" alt="screen shot 2019-02-19 at 1 53 22 pm" src="https://user-images.githubusercontent.com/12087705/53039711-bed0ec80-344d-11e9-8802-d11dbb294c9f.png">

### Browser/system information
This has been reproduced in the latest versions of the following browsers:
- Chrome for Mac (with Hypothesis extension and Via)
- Firefox for Mac (with Bookmarklet and Via)
- Safari for Mac (with Bookmarklet and Via)

### Additional details
- I can't really find a pattern determining when the client will show the Hypothesis logo properly and when it won't. 
- Interestingly, this doesn't seem to happen when publisher groups are present - you can switch back and forth between publisher groups and the org logo will always appear.

**Comment by hmstepanek** [comment]
I suspect this is a symptom of really slow logo requests in h. 
![image](https://user-images.githubusercontent.com/30059933/53115420-01043780-34fb-11e9-9950-8b226c10b053.png)
![image](https://user-images.githubusercontent.com/30059933/53115479-24c77d80-34fb-11e9-874c-5a5218aea8bb.png)

**Comment by hmstepanek** [comment]
It appears that this occurs when we use the default logo text rather than issuing a query to the server for the logo. Aka: in the client code if a group doesn't have a logo we autofill it with h's default logo and we have the hardcoded svg text stored in a constant at the top of the file. This appears for whatever reason to not be rendering correctly. 

Using server link:
![image](https://user-images.githubusercontent.com/30059933/53116932-aa98f800-34fe-11e9-9ee2-0978cbe1b898.png)

Using logo text provided in client constant:
![image](https://user-images.githubusercontent.com/30059933/53117001-cac8b700-34fe-11e9-98e6-13bdbd4931f9.png)
